version: '3.7'

services:
  app:
    build: ./docker
    init: true
    container_name: php7-app
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql5_7-db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dump/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASS}
    env_file:
      - ./.env
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-app
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
